// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    locked_asset_distribution
    (
        init => init
        upgrade => upgrade
        clearSingleValueMappers => clear_single_value_mappers
        clearCommunityDistributionList => clear_community_distribution_list
        clearUserLockedAssetMap => clear_user_locked_asset_map
        getUnlockPeriod => unlock_period
        getCommunityDistributionList => community_distribution_list
        getAssetTokenId => asset_token_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
