// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    timestamp_oracle
    (
        init => init
        upgrade => upgrade
        setStartTimestampForEpoch => set_start_timestamp_for_epoch
        overwriteStartTimestampForEpoch => overwrite_start_timestamp_for_epoch
        updateAndGetTimestampStartEpoch => update_and_get_timestamp_start_epoch
        getStartTimestampForEpoch => get_start_timestamp_for_epoch
        getStartTimestampMultipleEpochs => get_start_timestamp_multiple_epochs
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
