////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    simple_lock_energy
    (
        callBack
        acceptMigratedTokens
        addFarmToWhitelist
        addLiquidityLockedToken
        addLockOptions
        addLpToWhitelist
        enterFarmLockedToken
        exitFarmLockedToken
        extendLockingPeriod
        farmClaimRewardsLockedToken
        getBaseAssetTokenId
        getEnergyAmountForUser
        getEnergyEntryForUser
        getFarmProxyTokenId
        getFeesBurnPercentage
        getFeesCollectorAddress
        getKnownFarms
        getKnownLiquidityPools
        getLockOptions
        getLockedTokenId
        getLpProxyTokenId
        getOldTokenNonces
        getPenaltyAmount
        getPenaltyPercentage
        isPaused
        issueFarmProxyToken
        issueLockedToken
        issueLpProxyToken
        lockTokens
        pause
        reduceLockPeriod
        removeFarmFromWhitelist
        removeLiquidityLockedToken
        removeLockOptions
        removeLpFromWhitelist
        setFeesBurnPercentage
        setFeesCollectorAddress
        setOldLockedAssetFactoryAddress
        setPenaltyPercentage
        setTransferRoleLockedToken
        unlockEarly
        unlockTokens
        unpause
    )
}
