// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback:                       1
// Total number of exported functions:  17

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    farm_staking_proxy
    (
        stakeFarmTokens
        claimDualYield
        unstakeFarmTokens
        registerDualYieldToken
        getDualYieldTokenId
        getLpFarmAddress
        getStakingFarmAddress
        getPairAddress
        getStakingTokenId
        getFarmTokenId
        getLpTokenId
        getLpFarmTokenId
        addSCAddressToWhitelist
        removeSCAddressFromWhitelist
        isSCAddressWhitelisted
        callBack
    )
}
