// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    proxy_deployer
    (
        init => init
        upgrade => upgrade
        deployFarmStakingContract => deploy_farm_staking_contract
        removeAllByDeployer => remove_all_by_deployer
        removeSingleContract => remove_single_contract
        getDeployerType => deployer_type
        getTemplateAddress => template_address
        getAddressForToken => get_address_for_token
        getTokenForAddress => get_token_for_address
        getContractOwner => get_contract_owner
        getAllUsedTokens => get_all_used_tokens
        getAllDeployedContractsBySc => get_all_deployed_contracts_by_sc
        getAllDeployedContractsByUser => get_all_deployed_contracts_by_user
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
