// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback (empty):               1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    proxy_deployer
    (
        init => init
        upgrade => upgrade
        overwriteForcedDeployArgs => overwrite_forced_deploy_args
        deployContract => deploy_contract
        getTemplateAddress => template_address
        getAddressForToken => get_address_for_token
        getAllUsedTokens => get_all_used_tokens
        getAllDeployedContracts => get_all_deployed_contracts
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
