pub static EMISSION_RATE_ZERO: &[u8] = b"Emission rate cannot be zero";
pub static WEEK_ALREADY_INITIALIZED: &[u8] = b"Week already initialized";
pub static ALREADY_VOTED_THIS_WEEK: &[u8] = b"Already voted this week";
pub static INVALID_VOTE_AMOUNT: &[u8] = b"Invalid vote amount";
pub static INVALID_ESDT_IDENTIFIER: &[u8] = b"Invalid ESDT identifier";
pub static FARM_NOT_FOUND: &[u8] = b"Farm not found";
pub static INVALID_FARM_ADDRESS: &[u8] = b"Invalid farm address";
pub static FARM_NOT_WHITELISTED: &[u8] = b"Farm is not whitelisted";
pub static FARM_BLACKLISTED: &[u8] = b"Farm is blacklisted";
