[package]
name = "mex-governance-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.mex-governance]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "=0.53.2"
default-features = false
