// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    whitelists_hub
    (
        init => init
        upgrade => upgrade
        addAdmin => add_admin_endpoint
        removeAdmin => remove_admin_endpoint
        updateOwnerOrAdmin => update_owner_or_admin_endpoint
        getPermissions => permissions
        createWhitelist => create_whitelist
        addToWhitelist => add_to_whitelist
        removeFromWhitelist => remove_from_whitelist
        isWhitelisted => is_whitelisted
        getWhitelistAddresses => get_whitelist_addresses
        getAllWhitelists => get_all_whitelists
        countAddressesInWhitelist => count_addresses_in_whitelist
        getAllWhitelistInfo => get_all_whitelist_info
        batchIsWhitelisted => batch_is_whitelisted
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
