// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           25
// Async Callback:                       1
// Total number of exported functions:  27

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    proxy_dex
    (
        registerProxyPair
        setTransferRoleWrappedLpToken
        registerProxyFarm
        setTransferRoleWrappedFarmToken
        getAssetTokenId
        getLockedTokenIds
        getOldLockedTokenId
        getOldFactoryAddress
        getWrappedLpTokenId
        getWrappedFarmTokenId
        addPairToIntermediate
        removeIntermediatedPair
        addFarmToIntermediate
        removeIntermediatedFarm
        getIntermediatedPairs
        getIntermediatedFarms
        addLiquidityProxy
        removeLiquidityProxy
        enterFarmProxy
        exitFarmProxy
        claimRewardsProxy
        mergeWrappedFarmTokens
        mergeWrappedLpTokens
        setEnergyFactoryAddress
        getEnergyFactoryAddress
        callBack
    )
}
