// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           10
// Async Callback:                       1
// Total number of exported functions:  12

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    locked_token_wrapper
    (
        wrapLockedToken
        unwrapLockedToken
        issueWrappedToken
        setTransferRoleWrappedToken
        unsetTransferRoleWrappedToken
        getLockedTokenId
        getOldLockedTokenId
        getWrappedTokenId
        setEnergyFactoryAddress
        getEnergyFactoryAddress
        callBack
    )
}
