// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    distribution
    (
        setCommunityDistribution
        setPerUserDistributedLockedAssets
        claimLockedAssets
        clearUnclaimableAssets
        undoLastCommunityDistribution
        undoUserDistributedAssetsBetweenEpochs
        setUnlockPeriod
        calculateLockedAssets
        deleteUserDistributedLockedAssets
        getUsersDistributedLockedAssetsLength
        getUnlockPeriod
        getCommunityDistributionList
        getAssetTokenId
        startGlobalOperation
        endGlobalOperation
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
