////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    pair
    (
        addInitialLiquidity
        addLiquidity
        addTrustedSwapPair
        getAmountIn
        getAmountOut
        getBPAddConfig
        getBPRemoveConfig
        getBPSwapConfig
        getEquivalent
        getExternSwapGasLimit
        getFeeDestinations
        getFeeState
        getFirstTokenId
        getInitialLiquidtyAdder
        getLockingDeadlineEpoch
        getLockingScAddress
        getLpTokenIdentifier
        getNumAddsByAddress
        getNumRemovesByAddress
        getNumSwapsByAddress
        getReserve
        getReservesAndTotalSupply
        getRouterManagedAddress
        getRouterOwnerManagedAddress
        getSecondTokenId
        getSpecialFee
        getState
        getTokensForGivenPosition
        getTotalFeePercent
        getTotalSupply
        getTransferExecGasLimit
        getTrustedSwapPairs
        getUnlockEpoch
        getWhitelistedManagedAddresses
        pause
        removeLiquidity
        removeLiquidityAndBuyBackAndBurnToken
        removeTrustedSwapPair
        removeWhitelist
        resume
        setBPAddConfig
        setBPRemoveConfig
        setBPSwapConfig
        setFeeOn
        setFeePercents
        setLockingScAddress
        setLpTokenIdentifier
        setMaxObservationsPerRecord
        setStateActiveNoSwaps
        setUnlockEpoch
        set_extern_swap_gas_limit
        set_locking_deadline_epoch
        set_transfer_exec_gas_limit
        swapNoFeeAndForward
        swapTokensFixedInput
        swapTokensFixedOutput
        updateAndGetSafePrice
        updateAndGetTokensForGivenPositionWithSafePrice
        whitelist
    )
}

elrond_wasm_node::wasm_empty_callback! {}
