// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback:                       1
// Total number of exported functions:  21

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    simple_lock
    (
        lockTokens
        unlockTokens
        issueLockedToken
        getLockedTokenId
        issueLpProxyToken
        addLpToWhitelist
        removeLpFromWhitelist
        addLiquidityLockedToken
        removeLiquidityLockedToken
        getKnownLiquidityPools
        getLpProxyTokenId
        issueFarmProxyToken
        addFarmToWhitelist
        removeFarmFromWhitelist
        enterFarmLockedToken
        exitFarmLockedToken
        farmClaimRewardsLockedToken
        getKnownFarms
        getFarmProxyTokenId
        callBack
    )
}
