// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           25
// Async Callback:                       1
// Total number of exported functions:  27

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    simple_lock_whitelist
    (
        setTransferRoleLockedToken
        setTransferRoleProxyLpToken
        setTransferRoleProxyFarmToken
        setLockedToken
        lockTokens
        unlockTokens
        getTokenWhitelist
        issueLockedToken
        getLockedTokenId
        issueLpProxyToken
        addLpToWhitelist
        removeLpFromWhitelist
        addLiquidityLockedToken
        removeLiquidityLockedToken
        getKnownLiquidityPools
        getLpProxyTokenId
        issueFarmProxyToken
        addFarmToWhitelist
        removeFarmFromWhitelist
        enterFarmLockedToken
        exitFarmLockedToken
        farmClaimRewardsLockedToken
        getKnownFarms
        getFarmProxyTokenId
        exitFarmOldToken
        callBack
    )
}
