////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    farm_staking
    (
        init
        callBack
        addAddressToWhitelist
        calculateRewardsForGivenPosition
        claimRewards
        claimRewardsWithNewValue
        compoundRewards
        end_produce_rewards
        getAccumulatedRewards
        getAnnualPercentageRewards
        getBurnGasLimit
        getDivisionSafetyConstant
        getFarmTokenId
        getFarmTokenSupply
        getFarmingTokenId
        getFarmingTokenTotalLiquidity
        getLastErrorMessage
        getLastRewardBlockNonce
        getLockedAssetFactoryManagedAddress
        getMinUnbondEpochs
        getMinimumFarmingEpoch
        getOwner
        getPairContractManagedAddress
        getPenaltyPercent
        getPerBlockRewardAmount
        getRewardPerShare
        getRewardReserve
        getRewardTokenId
        getState
        getTransferExecGasLimit
        isWhitelisted
        mergeFarmTokens
        pause
        registerFarmToken
        removeAddressFromWhitelist
        resume
        setLocalRolesFarmToken
        setMaxApr
        setMinUnbondEpochs
        setPerBlockRewardAmount
        set_burn_gas_limit
        set_minimum_farming_epochs
        set_penalty_percent
        set_transfer_exec_gas_limit
        stakeFarm
        stakeFarmThroughProxy
        startProduceRewards
        topUpRewards
        unbondFarm
        unstakeFarm
        unstakeFarmThroughProxy
    )
}
