// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            2
// Async Callback (empty):               1
// Total number of exported functions:   4

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    pair_hooks_sample
    (
        init => init
        beforeAddInitialLiqHook => before_add_initial_liq_hook
        afterAddInitialLiqHook => after_add_initial_liq_hook
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
