////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    farm_with_community_rewards
    (
        callBack
        addAdmin
        addSCAddressToWhitelist
        addToPauseWhitelist
        calculateRewardsForGivenPosition
        claimRewards
        compoundRewards
        endProduceRewards
        enterFarm
        exitFarm
        getBoostedYieldsRewardsPercenatage
        getBurnGasLimit
        getCurrentWeek
        getDivisionSafetyConstant
        getEnergyFactoryAddress
        getFarmTokenId
        getFarmTokenSupply
        getFarmingTokenId
        getLastRewardBlockNonce
        getMinimumFarmingEpoch
        getPairContractManagedAddress
        getPenaltyPercent
        getPerBlockRewardAmount
        getPermissions
        getRewardPerShare
        getRewardReserve
        getRewardTokenId
        getState
        isSCAddressWhitelisted
        mergeFarmTokens
        pause
        registerFarmToken
        removeAdmin
        removeFromPauseWhitelist
        removeSCAddressFromWhitelist
        resume
        setBoostedYieldsRewardsPercentage
        setEnergyFactoryAddress
        setPerBlockRewardAmount
        set_burn_gas_limit
        set_minimum_farming_epochs
        set_penalty_percent
        startProduceRewards
    )
}
