// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           29
// Async Callback (empty):               1
// Total number of exported functions:  31

#![no_std]
#![feature(alloc_error_handler, lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    governance_v2
    (
        propose
        vote
        cancel
        withdrawDeposit
        changeMinEnergyForProposal
        changeMinFeeForProposal
        changeQuorumPercentage
        changeVotingDelayInBlocks
        changeVotingPeriodInBlocks
        getMinEnergyForPropose
        getMinFeeForPropose
        getQuorum
        getVotingDelayInBlocks
        getVotingPeriodInBlocks
        getFeeTokenId
        getWithdrawPercentageDefeated
        getProposals
        getUserVotedProposals
        getProposalVotes
        getProposalStatus
        getUserVotingPower
        getVotingPowerEquivalent
        getFeesCollectorAddress
        setEnergyFactoryAddress
        getEnergyFactoryAddress
        addAdmin
        removeAdmin
        updateOwnerOrAdmin
        getPermissions
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
