// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           43
// Async Callback (empty):               1
// Total number of exported functions:  46

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    fees_collector
    (
        init => init
        upgrade => upgrade
        addKnownContracts => add_known_contracts
        removeKnownContracts => remove_known_contracts
        addKnownTokens => add_known_tokens
        removeKnownTokens => remove_known_tokens
        getAllTokens => get_all_tokens
        getLockedTokenId => locked_token_id
        getAllKnownContracts => known_contracts
        getAllowExternalClaimRewards => allow_external_claim_rewards
        getLastActiveWeekForUser => get_last_active_week_for_user_view
        getUserEnergyForWeek => get_user_energy_for_week_view
        getLastGlobalUpdateWeek => last_global_update_week
        getTotalRewardsForWeek => total_rewards_for_week
        getTotalEnergyForWeek => total_energy_for_week
        getTotalLockedTokensForWeek => total_locked_tokens_for_week
        updateEnergyForUser => update_energy_for_user
        getCurrentClaimProgress => current_claim_progress
        depositSwapFees => deposit_swap_fees
        getAccumulatedFees => accumulated_fees
        setLockedTokensPerBlock => set_locked_tokens_per_block
        getLastLockedTokensAddWeek => last_locked_token_add_week
        getLockedTokensPerBlock => locked_tokens_per_block
        setLockingScAddress => set_locking_sc_address
        setLockEpochs => set_lock_epochs
        getLockingScAddress => locking_sc_address
        getLockEpochs => lock_epochs
        setEnergyFactoryAddress => set_energy_factory_address
        getEnergyFactoryAddress => energy_factory_address
        getCurrentWeek => get_current_week
        getFirstWeekStartEpoch => first_week_start_epoch
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        addSCAddressToWhitelist => add_sc_address_to_whitelist
        removeSCAddressFromWhitelist => remove_sc_address_from_whitelist
        isSCAddressWhitelisted => is_sc_address_whitelisted
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
        claimRewards => claim_rewards_endpoint
        claimBoostedRewards => claim_boosted_rewards
        redistributeRewards => redistribute_rewards
        getRemainingRewards => remaining_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
