// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           27
// Async Callback (empty):               1
// Total number of exported functions:  29

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    price_discovery_v1
    (
        init => init
        deposit => deposit
        withdraw => withdraw
        redeem => redeem
        getCurrentPrice => calculate_price
        getCurrentPhase => get_current_phase
        issueRedeemToken => issue_redeem_token
        createInitialRedeemTokens => create_initial_redeem_tokens
        setLockingScAddress => set_locking_sc_address
        setUnlockEpoch => set_unlock_epoch
        getLaunchedTokenId => launched_token_id
        getAcceptedTokenId => accepted_token_id
        getLaunchedTokenBalance => launched_token_balance
        getAcceptedTokenBalance => accepted_token_balance
        getStartBlock => start_block
        getEndBlock => end_block
        getRedeemTokenId => redeem_token_id
        getRedeemTokenTotalCirculatingSupply => redeem_token_total_circulating_supply
        getMinLaunchedTokenPrice => min_launched_token_price
        getPricePrecision => price_precision
        getNoLimitPhaseDurationBlocks => no_limit_phase_duration_blocks
        getLinearPenaltyPhaseDurationBlocks => linear_penalty_phase_duration_blocks
        getFixedPenaltyPhaseDurationBlocks => fixed_penalty_phase_duration_blocks
        getPenaltyMinPercentage => penalty_min_percentage
        getPenaltyMaxPercentage => penalty_max_percentage
        getFixedPenaltyPercentage => fixed_penalty_percentage
        getLockingScAddress => locking_sc_address
        getUnlockEpoch => unlock_epoch
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
