// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    proxy_dex_legacy
    (
        init => init
        getAssetTokenId => asset_token_id
        getLockedAssetTokenId => locked_asset_token_id
        getWrappedLpTokenId => wrapped_lp_token_id
        getWrappedFarmTokenId => wrapped_farm_token_id
        getIntermediatedFarms => get_intermediated_farms
        getIntermediatedPairs => get_intermediated_pairs
        addPairToIntermediate => add_pair_to_intermediate
        removeIntermediatedPair => remove_intermediated_pair
        removeLiquidityProxy => remove_liquidity_proxy
        addFarmToIntermediate => add_farm_to_intermediate
        removeIntermediatedFarm => remove_intermediated_farm
        exitFarmProxy => exit_farm_proxy
        setTransferRoleLockedLpToken => set_transfer_role_locked_lp_token
        unsetTransferRoleLockedLpToken => unset_transfer_role_locked_lp_token
        setTransferRoleLockedFarmToken => set_transfer_role_locked_farm_token
        unsetTransferRoleLockedFarmToken => unset_transfer_role_locked_farm_token
        getExtendedAttributesActivationNonce => extended_attributes_activation_nonce
        setEnergyFactoryAddress => set_energy_factory_address
        getEnergyFactoryAddress => energy_factory_address
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
