// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           38
// Async Callback (empty):               1
// Total number of exported functions:  40

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    farm_v13_custom_rewards
    (
        init => init
        addAddressToWhitelist => add_address_to_whitelist
        calculateRewardsForGivenPosition => calculate_rewards_for_given_position
        claimRewards => claim_rewards
        depositRewards => deposit_rewards
        end_produce_rewards => end_produce_rewards
        enterFarm => enter_farm
        exitFarm => exit_farm
        getBlockForEndRewards => block_for_end_rewards
        getBurnGasLimit => burn_gas_limit
        getDivisionSafetyConstant => division_safety_constant
        getFarmTokenId => farm_token_id
        getFarmTokenSupply => farm_token_supply
        getFarmingTokenId => farming_token_id
        getLastErrorMessage => last_error_message
        getLastRewardBlockNonce => last_reward_block_nonce
        getMinimumFarmingEpoch => minimum_farming_epochs
        getOwner => owner
        getPenaltyPercent => penalty_percent
        getPerBlockRewardAmount => per_block_reward_amount
        getRewardPerShare => reward_per_share
        getRewardReserve => reward_reserve
        getRewardTokenId => reward_token_id
        getState => state
        getTransferExecGasLimit => transfer_exec_gas_limit
        getWhitelist => whitelist
        mergeFarmTokens => merge_farm_tokens
        pause => pause
        registerFarmToken => register_farm_token
        removeAddressFromWhitelist => remove_address_from_whitelist
        resume => resume
        setBlockForEndRewards => set_block_for_end_rewards
        setLocalRolesFarmToken => set_local_roles_farm_token
        setPerBlockRewardAmount => set_per_block_reward_amount
        set_burn_gas_limit => set_burn_gas_limit
        set_minimum_farming_epochs => set_minimum_farming_epochs
        set_penalty_percent => set_penalty_percent
        set_transfer_exec_gas_limit => set_transfer_exec_gas_limit
        startProduceRewards => start_produce_rewards
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
