// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           32
// Async Callback:                       1
// Total number of exported functions:  34

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    energy_factory
    (
        lockTokens
        unlockTokens
        issueLockedToken
        getLockedTokenId
        getBaseAssetTokenId
        getLegacyLockedTokenId
        getEnergyEntryForUser
        getEnergyAmountForUser
        addLockOptions
        getLockOptions
        unlockEarly
        reduceLockPeriod
        getPenaltyAmount
        setTokenUnstakeAddress
        revertUnstake
        getTokenUnstakeScAddress
        setEnergyForOldTokens
        updateEnergyAfterOldTokenUnlock
        migrateOldTokens
        pause
        unpause
        isPaused
        setTransferRoleLockedToken
        setBurnRoleLockedToken
        mergeTokens
        lockVirtual
        addSCAddressToWhitelist
        removeSCAddressFromWhitelist
        isSCAddressWhitelisted
        addToTokenTransferWhitelist
        removeFromTokenTransferWhitelist
        setUserEnergyAfterLockedTokenTransfer
        callBack
    )
}
