// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    energy_factory_mock
    (
        init => init
        setUserEnergy => set_user_energy
        getEnergyAmountForUser => get_energy_amount_for_user
        getEnergyEntryForUser => get_energy_entry_for_user
        setUserEnergyAfterLockedTokenTransfer => set_user_energy_after_locked_token_transfer
        transferUnlockedToken => transfer_unlocked_token
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
