[package]
name = "metabonding-staking-legacy-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.metabonding-staking-legacy]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.60.0"
default-features = false
